version: '3.8'

services:
  api:
    build: .
    container_name: core_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      user_db:
        condition: service_healthy
      analysis_db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - core_network

  worker:
    build: .
    container_name: core_celery_worker
    command: celery -A worker.celery_app worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - user_db
      - analysis_db
    networks:
      - core_network

  user_db:
    image: postgres:15-alpine
    container_name: core_user_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: user_db
      POSTGRES_DB: user_db
    ports:
      - "5434:5432"
    volumes:
      - user_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - core_network

  analysis_db:
    image: postgis/postgis:15-3.3-alpine
    container_name: core_analysis_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: analysis_db
      POSTGRES_DB: analysis_db
    ports:
      - "5433:5432"
    volumes:
      - analysis_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - core_network

  redis:
    image: redis:7-alpine
    container_name: core_redis
    ports:
      - "6379:6379"
    networks:
      - core_network

volumes:
  user_postgres_data:
  analysis_postgres_data:

networks:
  core_network:
    driver: bridge